import type { PrismaticLayoutSnapshot } from "@prismatic/core"

/** Auto-generated by `npm run layout`. Edits here become the default layout for dev and build. */
export const PRISMATIC_LAYOUT: PrismaticLayoutSnapshot = {
  "positions": {
    "demo-title": {
      "x": 24,
      "y": 24
    },
    "demo-button": {
      "x": 434,
      "y": 746.7421875
    },
    "demo-slider": {
      "x": 712,
      "y": 746.7421875
    },
    "demo-image": {
      "x": 712,
      "y": 24
    },
    "demo-resolution": {
      "x": 360,
      "y": 746.7421875
    },
    "shortcuts": {
      "x": 20,
      "y": 468
    },
    "title-1": {
      "x": 360,
      "y": 24
    }
  },
  "sizes": {
    "demo-title": {
      "width": 209,
      "height": 35
    },
    "demo-button": {
      "width": 274,
      "height": 70
    },
    "demo-slider": {
      "width": 440,
      "height": 70
    },
    "demo-image": {
      "width": 366,
      "height": 366
    },
    "demo-resolution": {
      "width": 70,
      "height": 70
    },
    "shortcuts": {
      "width": 8,
      "height": 24
    },
    "title-1": {
      "width": 209,
      "height": 35
    },
    "image": {
      "width": 366,
      "height": 366
    }
  },
  "panelSettings": {
    "demo-title": {
      "titleSize": "small"
    },
    "demo-button": {
      "buttonSize": "medium"
    },
    "demo-slider": {
      "buttonSize": "medium"
    },
    "demo-image": {
      "titleSize": "large",
      "imageModules": 5
    },
    "demo-resolution": {
      "buttonSize": "small"
    },
    "shortcuts": {
      "titleSize": "small"
    },
    "title-1": {
      "titleSize": "small"
    },
    "image": {
      "titleSize": "large",
      "imageModules": 5
    }
  },
  "sliderColumnCount": 1,
  "imagePreviewModules": 5
}
