import type { PanelId, PanelSize, PixelPosition } from "../workspace/types"
import {
  derivePanelSettingsFromSnapshot,
  type PanelSettingsMap,
} from "./panelSettings"

export type PrismaticLayoutSnapshot = {
  positions: Record<PanelId, PixelPosition>
  sizes?: Record<PanelId, PanelSize>
  panelSettings?: PanelSettingsMap
  sliderColumnCount?: number
  imagePreviewModules?: number
}

export function createLayoutSnapshot(state: {
  uiPositions: Record<PanelId, PixelPosition>
  uiSizes: Record<PanelId, PanelSize>
  panelSettings: PanelSettingsMap
  sliderColumnCount: number
  imagePreviewModules: number
}): PrismaticLayoutSnapshot {
  return {
    positions: state.uiPositions,
    sizes: state.uiSizes,
    panelSettings: state.panelSettings,
    sliderColumnCount: state.sliderColumnCount,
    imagePreviewModules: state.imagePreviewModules,
  }
}

export function layoutSnapshotToStoreInit(
  snapshot: PrismaticLayoutSnapshot,
  options?: { layoutMode?: boolean },
) {
  const panelSettings =
    snapshot.panelSettings ??
    derivePanelSettingsFromSnapshot(snapshot.sizes)

  return {
    initialPositions: snapshot.positions,
    initialSizes: snapshot.sizes ?? {},
    panelSettings,
    sliderColumnCount: snapshot.sliderColumnCount,
    imagePreviewModules: snapshot.imagePreviewModules,
    layoutMode: options?.layoutMode,
  }
}

export function formatLayoutModule(snapshot: PrismaticLayoutSnapshot): string {
  const body = JSON.stringify(snapshot, null, 2)

  return [
    `import type { PrismaticLayoutSnapshot } from "@prismatic/core"`,
    ``,
    `/** Auto-generated by \`npm run layout\`. Edits here become the default layout for dev and build. */`,
    `export const PRISMATIC_LAYOUT: PrismaticLayoutSnapshot = ${body}`,
    ``,
  ].join("\n")
}
